dependencies:
  - python>=3.8
  - flask==2.1.3
  - flask_sqlalchemy==2.5.1
  - flask_marshmallow==0.14.0
  - marshmallow_sqlalchemy==0.28.0
  - marshmallow==3.19.0
  - flask_restful==0.3.9
  - flask_cors==3.0.10
  - psycopg2-binary==2.9.6
  - gunicorn==20.1.0
  - geopy==2.3.0
  - numpy==1.23.5
  - pandas==1.5.3
  - matplotlib==3.6.2
  - folium==0.14.0
  - leaflet==0.13.0
  - openai==0.27.10
  - boto3==1.26.70
  - requests==2.28.1
  - sqlalchemy==1.4.46
  - pillow==9.3.0

channels:
  - defaults
  - conda-forge
